### ISSUE TITLE
Documentation leads to server not found

### ISSUE THREAD

**Issue by ThatOneCalculator** [StarlaneStudios/Surrealist#193] opened 2024-04-21 21:27 UTC
https://github.com/StarlaneStudios/Surrealist?tab=readme-ov-file#how-to-use leads me to https://surrealist.starlane.studio/ which is non-existent

![image](https://github.com/StarlaneStudios/Surrealist/assets/44733677/78ffb298-2851-4ec6-b1ed-be8393165477)

**Comment by macjuul** [comment] 2024-04-21 22:19
Duplicate of https://github.com/StarlaneStudios/Surrealist/issues/186

I'll have this fixed very soon! 🙂

**Closed by macjuul** 2024-04-21 22:19 UTC
Labels: bug
