### ISSUE TITLE
Surrealist broken by specific Field Type

### ISSUE THREAD

**Issue by Autumnlight02** [StarlaneStudios/Surrealist#173] opened 2024-01-29 02:35 UTC
**Describe the bug**
This specific field type breaks surrealist.

**To Reproduce**
1. Create a new surrealdb etc..
2. run
```
DEFINE FIELD owner_document ON TABLE Perms TYPE record;
```
3. press on reload or reload the page. It cannot fetch the tables anymore.

**Expected behavior**
it works

**Environment (you can view the current version under Settings):**
 - Operating System Linux (running browser ver tho)
 - Surrealist Version 1.11.3
 - SurrealDB Version 1.1

EDIT: works fine if using:  TYPE record<string>
TODO: Fix at surrealist side, to see record; as record<string, number>

**Comment by macjuul** [comment] 2024-01-29 06:27
Duplicate of https://github.com/StarlaneStudios/Surrealist/issues/169

**Closed by macjuul** 2024-01-29 06:27 UTC
Labels: bug
