### ISSUE TITLE
When we type in the query editor, there is an offset between where we type and where the character shows, its confusing

### ISSUE THREAD

**Issue by rajasekarshanmugam** [StarlaneStudios/Surrealist#72] opened 2023-07-17 04:02 UTC
When we start typing in the query editor, as the number of characters increases, there seems to be some offset between what we type and where the character shows up .. mostly it shows somewhere to the right. and cursor sync is not right. This is causing a lot of confusion in adding/editing the query.

**To Reproduce**
1. cloned main branch, built the binaries on windows
2. started the program, connected to a server and in the query editor start typing query
3. when we type, notice that offset between where we type and where the characters appear. selecting text also selects incorrect areas.

**Expected behavior**
Custom position is where we expect text to be inserted and delete needs to remove characters on the right. Similarly selection has to show the right selected content - with no offset

**Environment (you can view the current version under Settings):**
 - Operating System - windows 11
 - Surrealist Version - main branch

GIF recording of the problem:
![queryteditor](https://github.com/StarlaneStudios/Surrealist/assets/5011723/c46d696c-6970-4ee0-8199-3ae901a49c5d)

**Comment by ItsMateo** [comment] 2023-07-17 11:12
Hey there and thanks for sending in this bug report! This is a seemingly rare issue, but you are not the first person to experience it. All the other reports surrounding this issue have seemingly been from Windows 11 users as well. With that being said however, I have tried several times to recreate this bug on Windows 11 and have not been successful.

To help assist us in trying to determine the cause of the bug, please answer the following:

Are you using any non-default font, text, or cursor settings? If so, could you please provide them here to the best of your ability?
Also, is your Surrealist UI zoomed in at all?

**Comment by rajasekarshanmugam** [comment] 2023-07-17 12:49
Thank you so much for the response. 

Custom font: no
Custom cursor: yes, zoomed a little
Custom mouse pointer: yes, zoomed a little

![image](https://github.com/StarlaneStudios/Surrealist/assets/5011723/8c3a8849-40f0-4df3-a7e7-23227d060461)
![image](https://github.com/StarlaneStudios/Surrealist/assets/5011723/de1d4da8-bf68-4d3b-bbab-31db24e92c0b)

also entire display - set to 125% to factor resolution
![image](https://github.com/StarlaneStudios/Surrealist/assets/5011723/ea7401d6-60e0-4aec-9b73-9db07eaf0de8)

Please let me know if you need any other details, glad to help.

**Comment by macjuul** [comment] 2023-08-02 19:45
This should be fixed in the next release

**Closed** 2023-08-10 14:44 UTC
Labels: bug
