### ISSUE TITLE
Explorer and Designer retrieve nothing in new SurrealDB version

### ISSUE THREAD

**Issue by nxfi777** [StarlaneStudios/Surrealist#161] opened 2023-12-23 00:12 UTC
**Describe the bug**
After upgrading to SurrealDB v1.0.2, the Explorer and Designer return no tables or records. My database does have content; queries still work and I can see all the data.

**To Reproduce**
1. Upgrade to SurrealDB v1.0.2
2. Click on Explorer/Designer

**Expected behavior**
All of my database tables and records should appear. 

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Windows 
 - Surrealist Version [e.g. 1.2.0]: 1.11.1
 - SurrealDB Version [execute "surreal version"]: 1.0.2 for linux on x86_64

**Comment by abrisene** [comment] 2023-12-28 09:44
May or may not be related to the issue you encountered -  I had a similar problem on a database instance, but the designer and explorer views would populate on others.

I rebuilt the schema piece by piece and tracked it down to an error in a schemaful table definition:

`DEFINE FIELD in ON identityOf TYPE record PERMISSIONS FULL;
DEFINE FIELD out ON identityOf TYPE record PERMISSIONS FULL;`

When I removed the typing and reinserted all the data, the tables reappeared. Obviously not an actual solution, but might be useful for debugging the cause.

**Comment by nxfi777** [comment] 2024-01-03 13:40
> May or may not be related to the issue you encountered - I had a similar problem on a database instance, but the designer and explorer views would populate on others.
> 
> I rebuilt the schema piece by piece and tracked it down to an error in a schemaful table definition:
> 
> `DEFINE FIELD in ON identityOf TYPE record PERMISSIONS FULL; DEFINE FIELD out ON identityOf TYPE record PERMISSIONS FULL;`
> 
> When I removed the typing and reinserted all the data, the tables reappeared. Obviously not an actual solution, but might be useful for debugging the cause.

This is actually an[ issue with SurrealDB](https://github.com/surrealdb/surrealdb/issues/3217) atm.

**Comment by macjuul** [comment] 2024-01-11 13:59
Is this issue still reproducible using [Surrealist 1.11.2](https://github.com/StarlaneStudios/Surrealist/releases/tag/v1.11.2) with SurrealDB 1.1?

**Comment by shadowbrok3r** [comment] 2024-01-11 14:25
@macjuul I can still reproduce this issue using Surrealist 1.11.2 with SurrealDB 1.1, I tried a database.surql with no records to rule bad data out, and also just tried a few simple lines in a surql file to make sure nothing else was an issue, but i still do not see anything, no tables, records, etc when i refresh.

**Comment by macjuul** [comment] 2024-01-11 14:31
@shadowbrok3r Could you share an example .surql with me so I could attempt to reproduce it? I'm personally not seeing any issues using SurrealDB 1.1 and Surrealist 1.11.2 on my production databases

**Comment by nxfi777** [comment] 2024-01-11 15:25
> Is this issue still reproducible using [Surrealist 1.11.2](https://github.com/StarlaneStudios/Surrealist/releases/tag/v1.11.2) with SurrealDB 1.1?

Upgraded to Surrealist 1.11.2 and SurrealDB 1.1, no fix. I feel that the problem has to do with [this SurrealDB issue](https://github.com/surrealdb/surrealdb/issues/3217)

**Comment by macjuul** [comment] 2024-01-11 16:31
It could very well be, it appears the surrealql parser is running into issues with record types without table names.

I'll go ahead and close this issue for now as it is likely unrelated to Surrealist

**Closed by macjuul** 2024-01-11 16:31 UTC
Labels: bug, awaiting response
