### ISSUE TITLE
can no longer connect after update from 1.6.1 > 1.6.2

### ISSUE THREAD

**Issue by keeganstothert** [StarlaneStudios/Surrealist#37] opened 2023-03-11 17:53 UTC
click connect and get this error `connection closed: unexpected connection close 1006`

The only way I could get it to work was to manually start a surreal instance in the CLI with args `surreal start --user root --pass root`

have these default credentials been removed? 

macos ventura 
version 1.6.2

**Comment by Roms1383** [comment] 2023-04-28 15:55
same error for me on `M1 Pro` chip, I also tried compiling from the sources but still got the error.
on the other side, REPL works fine. (I also started a surreal instance in the CLI)

macos ventura
version 1.6.4 / from sources at commit [3002726](https://github.com/StarlaneStudios/Surrealist/commit/30027262850d2e3aee6e8e4829c1c52c5d250368)

**Comment by Z8MB1E** [comment] 2023-05-01 04:29
I'm also having this issue!

**Comment by macjuul** [comment] 2023-05-01 16:01
Hey guys, I'm personally unable to reproduce this issue and since it appears to be so vague there's not much I can do about it right now. Perhaps if you open dev tools with `Ctrl + Shift + I` it may lead to a possible explanation, specifically the Console and Network tabs.

If anyone experiencing this issue is willing to investigate and submit a fix that too would be appreciated

**Comment by Roms1383** [comment] 2023-05-02 00:18
Ran the server like:

<img width="1512" alt="Screenshot 2566-05-02 at 07 07 10" src="https://user-images.githubusercontent.com/21016014/235552584-614511fb-fd7e-4616-953c-49b80b1936c2.png">

Checked the connection:

<img width="1512" alt="Screenshot 2566-05-02 at 07 05 21" src="https://user-images.githubusercontent.com/21016014/235552566-791fb97c-81e5-471c-96c2-9c248318c018.png">

Websocket connection is established then closed instantly:

<img width="1512" alt="Screenshot 2566-05-02 at 07 08 38" src="https://user-images.githubusercontent.com/21016014/235553198-50a11fdc-9a14-4ac4-8659-f918ee7c6e8e.png">
 
Looking at the security tab it seems to hint at `https` over `http`:
<img width="1011" alt="Screenshot 2566-05-02 at 07 09 31" src="https://user-images.githubusercontent.com/21016014/235553250-6a3506d5-4555-4b2c-be39-590b96ea4180.png">

But I couldn't find any documentation on how to potentially specify e.g. `https` certificate @macjuul.

**Comment by macjuul** [comment] 2023-05-02 05:40
Thanks a lot @Roms1383. have you tried using localhost or 127.0.0.1 as the hostname yet? (with the same port)

**Comment by Roms1383** [comment] 2023-05-03 01:03
Ok I'm trying it now and got it to work with both `localhost` and `127.0.0.1`! @macjuul 
As far as I remember, I'm currently on the version built from sources.
<img width="1457" alt="Screenshot 2566-05-03 at 08 02 09" src="https://user-images.githubusercontent.com/21016014/235815632-0d2a8255-ab0c-40ad-8c4e-3066872be596.png">

**Comment by Nipodemos** [comment] 2023-05-13 17:28
just to add to that, i'm having the same issue, as soon as I try to connect using surrealist, the SurrealDB cli shows this error:
```
←[2m2023-05-13T17:21:39.299330Z←[0m ←[32m INFO←[0m ←[1msurrealdb::net←[0m←[2m:←[0m 127.0.0.1:61857 GET /rpc HTTP/1.1 101 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35" 109.3µs
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("invalid type: sequence, expected a string")', lib\src\sql\statements\define.rs:555:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

here's a screenshot in case you prefer
![image](https://github.com/StarlaneStudios/Surrealist/assets/11494727/eb21de2f-af66-436f-b077-a5ac80805ee9)

i'm using localhost to try to connect
![image](https://github.com/StarlaneStudios/Surrealist/assets/11494727/7b4c0227-3a5c-46af-9457-b3419b1c9531)
my current version of surrealist is `Version 1.7.1 by Starlane Studios`
my version of surrealdb is `1.0.0-beta.9+20230402.5eafebd for windows on x86_64`

**Comment by macjuul** [comment] 2023-05-13 17:31
> just to add to that, i'm having the same issue, as soon as I try to connect using surrealist, the SurrealDB cli shows this error:
> 
> ```
> ←[2m2023-05-13T17:21:39.299330Z←[0m ←[32m INFO←[0m ←[1msurrealdb::net←[0m←[2m:←[0m 127.0.0.1:61857 GET /rpc HTTP/1.1 101 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35" 109.3µs
> thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("invalid type: sequence, expected a string")', lib\src\sql\statements\define.rs:555:72
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> here's a screenshot in case you prefer ![image](https://user-images.githubusercontent.com/11494727/238149017-eb21de2f-af66-436f-b077-a5ac80805ee9.png)
> 
> i'm using localhost to try to connect ![image](https://user-images.githubusercontent.com/11494727/238149043-7b4c0227-3a5c-46af-9457-b3419b1c9531.png) my current version of surrealist is `Version 1.7.1 by Starlane Studios` my version of surrealdb is `1.0.0-beta.9+20230402.5eafebd for windows on x86_64`

This appears to be a SurrealDB internal error unrelated to Surrealist. Usually this indicates some sort of invalid data, which I personally experienced when updating to beta 9 ([This helped me fix it](https://surrealdb.com/docs/installation/upgrading/beta8-to-beta9))

**Comment by Nipodemos** [comment] 2023-05-13 18:50
> 
> This appears to be a SurrealDB internal error unrelated to Surrealist. Usually this indicates some sort of invalid data, which I personally experienced when updating to beta 9 ([This helped me fix it](https://surrealdb.com/docs/installation/upgrading/beta8-to-beta9))

Thank you for this, doing the guide worked for me. I wasn't aware of this required steps to migrate

**Comment by macjuul** [comment] 2023-06-12 08:13
I'll close this issue for now. If anyone experiences further connection problems feel free to open a new issue

**Closed by macjuul** 2023-06-12 08:13 UTC
Labels: bug
