### ISSUE TITLE
Flash of white background

### ISSUE THREAD

**Issue by oskar-gmerek** [StarlaneStudios/Surrealist#11] opened 2023-01-09 20:46 UTC
**Describe the bug**
When I change from table to json view in the result options. Every time I see a flash of the white background of the query and variable sections (only on this two sections). 

**To Reproduce**
1. Install Surrealist 1.4.1 on macOS (amd) with dark mode active
2. Click on table view and then change to json view again
3. See the flash of white background

**Expected behavior**
Don't flash my eyes 👀

**Environment (you can view the current version under Settings):**
 - OS: macOS Ventura 13.0.1 (amd)
 - Surrealist Version: 1.4.1

**Comment by macjuul** [comment] 2023-01-13 18:59
This is definitely odd, however I am unable to reproduce it on Windows. My immediate guess is this is related to the Monaco editors, however since I'm unable to debug this issue myself I'll like to keep it open for others who can reproduce and potentially submit a fix.

Sorry for the flashbangs!

**Comment by macjuul** [comment] 2023-02-04 23:32
This should be fixed in 1.5.1. If you still experience the flashing please reopen the issue

**Closed by macjuul** 2023-02-04 23:32 UTC
Labels: bug, help wanted
