### ISSUE TITLE
Surrealist stops processing after performing certain operations

### ISSUE THREAD

**Issue by Z8MB1E** [StarlaneStudios/Surrealist#102] opened 2023-09-08 03:11 UTC
**Describe the bug**
When launching Surrealist and attempting to select from a table or use the Explorer view, the app stops processing all further commands, no longer sends queries, does not return any data, and effectively becomes completely unusable until a restart (sometimes multiple restarts before working again.)

**To Reproduce**
1. Launch Surrealist.
2. Connect to SurrealDB endpoint.
3. Run `info for kv;` command to test responsiveness.
4. Open Explorer view, select a table, and click "Refresh" on the Record Explorer panel. (At this point, no records appear.)
5. Return to Query view and run `info for kv;` or `info for db;` command to test responsiveness. (At this point, nothing is returned and there is no visible change in the interface indicating a successful operation.)
6. Run `select * from [table]` where [table] is replaced with the name of a table. (Nothing happens.)
7. Disconnect from endpoint and attempt to reconnect. (At this point, the connection button changes to an infinite "Connecting..." state.)
8. Restart Surrealist and try again.

**Expected behavior**
When clicking "Refresh" in step 4, Surrealist should display contained data. The entire app stops working after this point as well. Data can be entered into the database via SurrealDB's CLI tool, but apparently not via Surrealist.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Windows 10
 - Surrealist Version [e.g. 1.2.0]: `1.9.0`
 - SurrealDB Version [execute "surreal version"]: `1.0.0-beta.11+20230905.59718fc for windows on x86_64`

**Comment by Black1358** [comment] 2023-09-08 13:00
I'm facing the same problem

**Comment by macjuul** [comment] 2023-09-08 18:19
I can confirm this happening myself. I have yet to determine the specific cause although it's likely due to a locking mutex in the Rust backend.

**Comment by Black1358** [comment] 2023-09-09 04:30
![изображение](https://github.com/StarlaneStudios/Surrealist/assets/122863429/66330292-f943-496c-b9f0-afc6ef4314ac)
And now the WEB-verson doesn't work too)

**Comment by Z8MB1E** [comment] 2023-09-09 05:09
> I can confirm this happening myself. I have yet to determine the specific cause although it's likely due to a locking mutex in the Rust backend.

Good to know it's not just me. Looking forward to any fix as soon as you have it available! Surrealist is probably my favorite tool for working with this DB.

**Comment by macjuul** [comment] 2023-09-09 10:14
@Black1358 My apologies, this was an unrelated issue in the new release I'm working on. I'll have this fixed shortly

**Comment by macjuul** [comment] 2023-09-09 13:18
The latest 1.9.1 release contains a potential fix for this issue. I'd love to hear if it solves your problems

**Comment by Z8MB1E** [comment] 2023-09-09 20:31
> The latest 1.9.1 release contains a potential fix for this issue. I'd love to hear if it solves your problems

After some brief testing, it appears your fixes worked. If anything else comes up as I get more thorough, I'll be sure to let you know!

**Comment by Z8MB1E** [comment] 2023-09-09 21:30
Okay, just saw a new issue... it appears that the _default_ field accepts input but does not push to the DB. When you attempt to save a default value using that input field, reopening the column definition shows that nothing was saved to that default field. The old method of manually assigning the value (ie. `$value OR $before OR 'default_value'`) appears to work.

**Comment by Black1358** [comment] 2023-09-10 04:21
Everything works for me and I didn't find any problems)

**Closed** 2023-09-10 11:46 UTC
Labels: bug, awaiting response
