### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by ntorrey** [StarlaneStudios/Surrealist#135] opened 2023-10-26 21:09 UTC
**Describe the bug**
It seems that the pagination is "stuck" on only the first page of results.

**To Reproduce**
In the explorer, open a table that contains many records. Only the first page is accessible.

**Expected behavior**
I expect all the results to be available via pagination.

**Environment:**
 - Operating System: Windows 11
 - Surrealist Version: 1.10.3
 - SurrealDB Version: surrealdb-1.0.0+20231019.f185c59

**Comment by macjuul** [comment] 2023-10-26 22:32
Duplicate of #133. Already fixed and will be released soon!

**Closed by macjuul** 2023-10-26 22:32 UTC
Labels: bug
